/// <reference types="react-native-css/types" />

/**
 * Ambient declarations for the Reach app.
 *
 * `nativewind-env.d.ts` is generated by react-native-css and must keep this
 * name — see https://www.nativewind.dev/v5/getting-started/installation
 * for the list of filenames TypeScript refuses to pick up.
 */

declare module '*.css';

declare module '*.ttf' {
  const content: number;
  export default content;
}
